### ISSUE TITLE
Option for orientation.

### ISSUE THREAD

**Issue by pravinarr** [namannehra/flipping-pages#1]
Hello,

Is there an option to change the orientation to horizontal?

thank you in advance

**Comment by namannehra** [comment]
There is no such option right now

**Comment by namannehra** [comment]
I have updated it with support for horizontal mode along with other improvements. I don't have access to a Mac or iOS device so I can't test it on them. Once I can verify that it works on iOS I'll publish the update on npm.

**Comment by namannehra** [comment]
Added in version 2.0.0
