### ISSUE TITLE
Page Links

### ISSUE THREAD

**Issue by jeffrainey** [namannehra/flipping-pages#29]
First, great tool, I love it! I used it to make this: https://sketchyplayground.com/

Do you already have a way that you work with adding links in the page? Maybe a way to designate the touch on the link should be treated differently than anywhere else on the page?

**Comment by namannehra** [comment]
Here is an example with a link inside the page. It works by checking if the event is fired by the link using the `onSwipeStart` prop.
https://codesandbox.io/s/empty-fire-5wou18?file=/src/App.js

Another way would be to stop the propagation of `pointerdown` event on the link.

You can also make it work for all links by doing something link this: https://stackoverflow.com/questions/58899301/find-out-if-an-element-is-a-descendant-of-a-specific-element-type

**Comment by jeffrainey** [comment]
Thanks for the response! I like the first route but when you turn that page and then back again the link stops working. I found this because my link is on page 4 and I was having trouble getting it to work. I will continue to try and figure out the root of this issue tomorrow.

**Comment by namannehra** [comment]
I have added `noSwipeClass` prop in v3.1.0. @jeffrainey Can you check if it works correctly for you?

**Comment by jeffrainey** [comment]
I updated to 3.1 and added the onSwipeStart callback for the tagname like your example and it works perfectly!

Thanks so much!
