### ISSUE TITLE
Content interaction

### ISSUE THREAD

**Issue by gspereira** [namannehra/flipping-pages#37]
I'm trying to implement this on a project, but I want the content of the page to be interactive, having buttons and such, but I couldn't find a way to implement it without having to disable swipe controls.
Is there any other way?

**Comment by namannehra** [comment]
Can you provide an example along with information about the device you placed issues on. (OS and browser names and versions)

I tested it on iOS by putting a button on a page. Both button click and swipe controls worked.

**Comment by gspereira** [comment]
Im using windows, browser is Edge.
Ill put an example of the code, its a very early implementation, but I want to make sure before commiting to the component.

```
<FlippingPages
    direction="right-to-left"
    animationDuration={800}
    disableSwipe={true}
    onSwipeEnd={setSelected}
    selected={selected}
>
    <BookPage pageNum={"page1"} />
    <BookPage pageNum={"page2"} />
    <BookPage pageNum={"page3"} />
</FlippingPages>

```


And this is the content of the BookPage component

```
<Box className={`page ${pageNum}`}>
    <p>{counter}</p>
    <button onClick={handleClick}>Click me</button>
</Box>
```

**Comment by namannehra** [comment]
Can you check if version `3.1.1-beta-0` fixes your issue?

Branch: https://github.com/namannehra/flipping-pages/tree/v3.1.1

**Comment by gspereira** [comment]
Had no luck

**Comment by gspereira** [comment]
OK, was a problem with Z-Index, completely my fault. Thank you very much.
