### ISSUE TITLE
window reference error when building on server

### ISSUE THREAD

**Issue by clairefro** [namannehra/flipping-pages#6]
This module throws an error when building react site for deployment since the `window` is not available to node.js. Likely it has to do with the naked `addEventListener`/`removeEventListener` s in FlippingPages.js.  Is there a way to prevent binding the listener to the window, for a build-friendly approach?

```
10:46:29 PM:   WebpackError: ReferenceError: window is not defined
10:46:29 PM:   
10:46:29 PM:   - FlippingPages.js:1 Object../node_modules/flipping-pages/FlippingPages.js
10:46:29 PM:     node_modules/flipping-pages/FlippingPages.js:1:441
```

**Comment by namannehra** [comment]
You can render `FlippingPages` after mounting as a workaround.

```
const App = () => {

    const [mounted, setMounted] = useState(false)
    useEffect(() => {
        setMounted(true)
    }, [])

    if (!mounted) {
        return null
    }

    return (
        <FlippingPages></FlippingPages>
    )

}
```

**Comment by namannehra** [comment]
All calls to `addEventListener/removeEventListener` are made in `componentDidMount/componentWillUnmount`. Not sure where the error is coming from. Make sure the error is not caused by a child a of `FlippingPages` using window before mounting.
